const productsList = [
  {
    id_product: 1,
    category: "alt-rock",
    fk_idcategorys: 1,
    name_product: "Wasting Light",
    artist: "Foo Fighters",
    image: "./images/produtos/ff-wl.jpg",
    id_categorys: 1,
    name_categorys: "Alternative Rock",
    selected: false,
  },
  {
    id_product: 2,
    category: "prg-rock",
    fk_idcategorys: 4,
    name_product: '"Heroes"',
    artist: "David Bowie",
    image: "./images/produtos/db-h.jpg",
    id_categorys: 4,
    name_categorys: "Progressive Rock",
    selected: false,
  },
  {
    id_product: 3,
    category: "rock",
    fk_idcategorys: 2,
    name_product: "Tattoo You",
    artist: "The Rolling Stones",
    image: "./images/produtos/trs-ty.jpg",
    id_categorys: 2,
    name_categorys: "Classic Rock",
    selected: false,
  },
  {
    id_product: 4,
    category: "rock",
    fk_idcategorys: 2,
    name_product: "Rumours",
    artist: "Fleetwood Mac",
    image: "./images/produtos/fm-r.jpg",
    id_categorys: 2,
    name_categorys: "Classic Rock",
    selected: false,
  },
  {
    id_product: 5,
    category: "alt-rock",
    fk_idcategorys: 1,
    name_product: "Elephant",
    artist: "The White Stripes",
    image: "./images/produtos/tws-e.png",
    id_categorys: 1,
    name_categorys: "Alternative Rock",
    selected: false,
  },
  {
    id_product: 6,
    category: "pnk-rock",
    fk_idcategorys: 3,
    name_product: "American Idiot",
    artist: "Green Day",
    image: "./images/produtos/gd-ai.jpg",
    id_categorys: 3,
    name_categorys: "Punk Rock",
    selected: false,
  },
  {
    id_product: 7,
    category: "rock",
    fk_idcategorys: 2,
    name_product: "Bella Donna",
    artist: "Stevie Nicks",
    image: "./images/produtos/sn-bd.jpg",
    id_categorys: 2,
    name_categorys: "Classic Rock",
    selected: false,
  },
  {
    id_product: 8,
    category: "alt-rock",
    fk_idcategorys: 1,
    name_product: "Californication",
    artist: "Red Hot Chili Peppers",
    image: "./images/produtos/rhcp-c.jpg",
    id_categorys: 1,
    name_categorys: "Alternative Rock",
    selected: false,
  },
  {
    id_product: 9,
    category: "alt-rock",
    fk_idcategorys: 1,
    name_product: "Nevermind",
    artist: "Nirvana",
    image: "./images/produtos/n-nvm.jpg",
    id_categorys: 1,
    name_categorys: "Alternative Rock",
    selected: false,
  },
  {
    id_product: 10,
    category: "rock",
    fk_idcategorys: 2,
    name_product: "Permanent Vacation",
    artist: "Aerosmith",
    image: "./images/produtos/a-pv.jpg",
    id_categorys: 2,
    name_categorys: "Classic Rock",
    selected: false,
  },
  {
    id_product: 11,
    category: "alt-rock",
    fk_idcategorys: 1,
    name_product: "...Like Clockwork",
    artist: "Queens of the Stone Age",
    image: "./images/produtos/qotsa-lc.png",
    id_categorys: 1,
    name_categorys: "Alternative Rock",
    selected: false,
  },

  {
    id_product: 12,
    category: "hard-rock",
    fk_idcategorys: 5,
    name_product: "Bat Out of Hell",
    artist: "Meat Loaf",
    image: "./images/produtos/ml-booh.jpg",
    id_categorys: 5,
    name_categorys: "Hard Rock",
    selected: false,
  },
];

export default productsList;
